### ISSUE TITLE
Update to new ingress api

### ISSUE THREAD

**Issue by ariep** [nikdoof/helm-charts#26]
The `deluge` chart (maybe others as well, haven't checked that) still uses the old `extensions/v1beta1` api for ingress. That has been deprecated for some time, being replaced by the `networking.k8s.io/v1` version. From kubernetes 1.22 on, the old api is no longer available.

**Comment by nikdoof** [comment]
I'd suggest using the [k8s-at-home Deluge chart](https://github.com/k8s-at-home/charts/tree/master/charts/stable/deluge), I've also switched over to using it and I'll be removing the `deluge` chart from this repository very soon. My chart offers no extra features over the k8s-at-home one and in fact is a little bit too complicated for its own good due to the multiple service endpoints to fight around the no mixed LB protocols, which is now a feature flag in newer Kubernetes versions.
